services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data_vol:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
    networks:
      - nos3-core

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: ${COMPOSE_PROJECT_NAME}-logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ../attack_logs:/attack_logs:ro
      - ../omni_logs:/omni_logs:ro
      - ../cfg/build/elk:/etc/logstash/mid:ro
    networks:
      - nos3-core
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: ${COMPOSE_PROJECT_NAME}-kibana
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - nos3-core
    depends_on:
      - elasticsearch

networks:
  nos3-core:
    name: ${NETWORK_NAME}
    external: true

volumes:
  es_data_vol:
