input {
  # LAYER 1: The Software Bus "God View"
  file {
    path => "/attack_logs/cfs_god_view.json"
    start_position => "beginning"
    codec => "json"
    type => "software_bus"
  }

  # LAYER 2: The Omni-Logs (Hardware, Physics, OS, Radio)
  file {
    path => "/omni_logs/*.log"
    start_position => "beginning"
    type => "system_log"
  }
}

filter {
  if [type] == "system_log" {
    # Extract the subsystem name right out of the log file's name
    grok {
      match => { "path" => ".*/%{GREEDYDATA:subsystem}\.log" }
    }
    
    # Clean up the name so it looks pretty in Kibana
    mutate {
      gsub => [
        "subsystem", "sc01_-_", ""
      ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "nos3-telemetry-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}