input {
  # LAYER 1: The Software Bus "God View"
  file {
    path => "/attack_logs/cfs_god_view.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
    type => "software_bus"
  }

  # LAYER 2: The Omni-Logs (Hardware, Physics, OS, Radio)
  file {
    path => "/omni_logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "system_log"
  }
}

filter {
  if [type] == "software_bus" {
    translate {
      field => "msg_id"
      destination => "msg_name"
      dictionary => {
        "0x1806" => "CFE_ES_CMD_MID"
        "0x1808" => "CFE_ES_SEND_HK_MID"
        "0x0800" => "CFE_ES_HK_TLM_MID"
        "0x080B" => "CFE_ES_APP_TLM_MID"
        "0x0810" => "CFE_ES_MEMSTATS_TLM_MID"
        "0x1803" => "CFE_SB_CMD_MID"
        "0x180B" => "CFE_SB_SEND_HK_MID"
        "0x0803" => "CFE_SB_HK_TLM_MID"
        "0x080A" => "CFE_SB_STATS_TLM_MID"
      }
      fallback => "UNKNOWN_MSG"
    }
  }

  if [type] == "system_log" {
    grok {
      match => { "path" => ".*/%{GREEDYDATA:subsystem}\.log" }
    }
    mutate {
      gsub => [
        "subsystem", "sc01_-_", ""
      ]
    }
    kv {
      source => "message"
      value_split => "=:"
      field_split => " ,"
      trim_key => "\[\]\(\)\s"
      trim_value => "\[\]\(\)\s"
    }
    mutate {
      convert => {
        "TOTAL_CPU_PCT" => "float"
        "CPU_PCT"       => "float"
        "NUM_PIDS"      => "integer"
        "CMDCOUNTER"    => "integer"
        "ERRCOUNTER"    => "integer"
        "PINGCOUNTER"   => "integer"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "nos3-telemetry-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}