#!/usr/bin/env bash
# =============================================================================
# Piggyback PoC comparison harness (secured fork side)
# =============================================================================
# Runs the identical piggyback attack on THIS (secured) NOS3 fork, scenario by
# scenario, and reports the detection + autonomous-response signatures observed
# in Elasticsearch. Pair the output with the Draco baseline column in
# docs/security/comparison-secured-vs-draco.md.
#
# It does NOT relaunch the stack by default - bring it up first with
# `make launch` (the noisy_app row must be CFE_APP and the FSW rebuilt). Use it
# from the repo's nos3/ directory.
#
# Usage:
#   nos3/poc/piggyback_noisy/run_comparison.sh [--es URL] [--with-flood] [--save]
#     --es URL       Elasticsearch base (default http://localhost:9200)
#     --with-flood   also run the DESTRUCTIVE SB_FLOOD (0x08) scenario LAST
#     --save         `make save-run RUN_LABEL=secured_<scenario>` after each run
#
# Each scenario records the ES doc count for its expected signatures within the
# scenario's own time window, so counts are attributable to that scenario.
# =============================================================================
set -u

ES="http://localhost:9200"
WITH_FLOOD=0
SAVE=0
HERE="$(cd "$(dirname "$0")" && pwd)"
DRIVER="$HERE/drive_poc.py"
NOS3_DIR="$(cd "$HERE/../.." && pwd)"   # .../nos3
OUT="$HERE/results_secured.md"

while [ $# -gt 0 ]; do
  case "$1" in
    --es) ES="$2"; shift 2;;
    --with-flood) WITH_FLOOD=1; shift;;
    --save) SAVE=1; shift;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# es_count <since_iso> <key> <value> : count docs with key==value since timestamp
es_count() {
  local since="$1" key="$2" val="$3"
  local body
  body=$(cat <<JSON
{"query":{"bool":{"must":[
  {"term":{"$key":"$val"}},
  {"range":{"@timestamp":{"gte":"$since"}}}
]}}}
JSON
)
  curl -s "$ES/nos3-telemetry-*/_count" -H 'Content-Type: application/json' \
       -d "$body" 2>/dev/null \
    | python3 -c 'import sys,json;
try:
  print(json.load(sys.stdin).get("count",0))
except Exception:
  print(-1)'
}

report_scenario() {
  # report_scenario <label> <since> <tag1,tag2,...>
  local label="$1" since="$2" tags="$3"
  echo "### $label" | tee -a "$OUT"
  echo "" | tee -a "$OUT"
  echo "| signature (tag) | docs since $since |" | tee -a "$OUT"
  echo "|---|---|" | tee -a "$OUT"
  local IFS=','
  for t in $tags; do
    local c; c=$(es_count "$since" "tags.keyword" "$t")
    printf "| %s | %s |\n" "$t" "$c" | tee -a "$OUT"
  done
  # also report low-battery telemetry excursions and any RTS-fired EVS
  local bat; bat=$(curl -s "$ES/nos3-telemetry-*/_count" -H 'Content-Type: application/json' \
      -d "{\"query\":{\"bool\":{\"must\":[{\"range\":{\"eps_battery_mv\":{\"lt\":24240}}},{\"range\":{\"@timestamp\":{\"gte\":\"$since\"}}}]}}}" 2>/dev/null \
      | python3 -c 'import sys,json;
try: print(json.load(sys.stdin).get("count",0))
except Exception: print(-1)')
  printf "| eps_battery_mv < 24240 | %s |\n" "$bat" | tee -a "$OUT"
  local rts; rts=$(curl -s "$ES/nos3-telemetry-*/_count" -H 'Content-Type: application/json' \
      -d "{\"query\":{\"bool\":{\"must\":[{\"match_phrase\":{\"evs_message\":\"SciMode: Low Power\"}},{\"range\":{\"@timestamp\":{\"gte\":\"$since\"}}}]}}}" 2>/dev/null \
      | python3 -c 'import sys,json;
try: print(json.load(sys.stdin).get("count",0))
except Exception: print(-1)')
  printf "| RTS 27 fired (SciMode: Low Power EVS) | %s |\n" "$rts" | tee -a "$OUT"
  echo "" | tee -a "$OUT"
}

run_scenario() {
  # run_scenario <mode> <label> <settle_secs> <tags>
  local mode="$1" label="$2" settle="$3" tags="$4"
  local since; since="$(now_iso)"
  echo ">>> [$label] driving '$mode' (settle ${settle}s)"
  python3 "$DRIVER" "$mode"
  sleep "$settle"
  report_scenario "$label" "$since" "$tags"
  if [ "$SAVE" -eq 1 ]; then
    ( cd "$NOS3_DIR" && make save-run RUN_LABEL="secured_${mode}" ) || \
      echo "warn: save-run failed for $mode" >&2
  fi
}

{
  echo "# Piggyback PoC - secured fork measured signatures"
  echo ""
  echo "Generated by run_comparison.sh against $ES."
  echo "Each table counts ES docs within that scenario's own time window."
  echo ""
} > "$OUT"

# quick reachability check
if [ "$(curl -s -o /dev/null -w '%{http_code}' "$ES" 2>/dev/null)" != "200" ]; then
  echo "ERROR: Elasticsearch not reachable at $ES (is the stack launched?)" >&2
  exit 1
fi

# 1. ladder: control NOOP + EPS_SPOOF(0x02) + SB_BURST(0x04)
run_scenario ladder "Ladder (control + EPS_SPOOF 0x02 + SB_BURST 0x04)" 20 \
  "attack_loaded,attack_piggyback,attack_eps_spoof,attack_sb_burst,piggyback_carrier,piggyback_length_error"

# 2. override: arm AP#27 + persistent EPS override (0x06) -> RTS 27
run_scenario override "EPS_OVERRIDE (0x06) -> autonomous RTS 27" 30 \
  "attack_piggyback,attack_eps_override,piggyback_carrier"

# 3. clear the override so the stack is left in a sane state
run_scenario off "Clear override (0x00 DORMANT)" 8 \
  "attack_piggyback,attack_eps_override"

# 4. optional destructive SB_FLOOD - run last
if [ "$WITH_FLOOD" -eq 1 ]; then
  echo ">>> WARNING: SB_FLOOD is destructive; the sim will go dark and need a relaunch."
  run_scenario flood "SB_FLOOD (0x08) - destructive pool lock" 15 \
    "attack_piggyback,attack_sb_flood,sb_pipe_overflow,noisy_app_spam_target"
fi

echo ""
echo "Done. Results written to $OUT"
echo "Paste the measured column into docs/security/comparison-secured-vs-draco.md."
