#!/usr/bin/env python3
"""
god_view_capture.py - Headless CCSDS Software Bus packet logger for NOS3.

Sends a TO_LAB_OUTPUT_ENABLE_CC command to CI_LAB so the telemetry output
app begins forwarding all Software Bus packets to a UDP port.  Listens on
that port, parses each packet's CCSDS primary header, and appends a JSON
line to attack_logs/cfs_god_view.json for every packet received.

Re-sends the enable command every ENABLE_INTERVAL_S seconds so it survives
CI restarts or command counter resets.

Usage (background):
    python3 scripts/god_view_capture.py &

Stop:
    pkill -f god_view_capture.py
"""

import fcntl
import json
import math
import os
import signal
import socket
import struct
import sys
import threading
import time

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
def _discover_ci_lab_ip() -> str:
    """Resolve the CI_LAB container IP via docker inspect, fall back to static.

    CI_LAB is bundled into the cFS FSW container (sc01-nos-fsw) on the
    nos3-sc01 spacecraft network, NOT on nos3-core. The legacy fallback of
    172.19.0.4 (a nos3-core address) silently mis-targeted enable commands
    away from the FSW; check sc01-nos-fsw first.
    """
    import subprocess
    for name in ("sc01-nos-fsw", "nos3-sc01-ci-lab", "nos3-ci-lab", "sc01-ci-lab"):
        try:
            result = subprocess.run(
                ["docker", "inspect", name,
                 "--format", "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"],
                capture_output=True, text=True, timeout=5,
            )
            ip = result.stdout.strip().split("\n")[0]
            if ip:
                return ip
        except Exception:
            pass
    return "172.21.0.4"  # nos3-sc01 default for static-network deployments

CI_LAB_HOST        = _discover_ci_lab_ip()  # IP of the FSW container on nos3-sc01 network
CI_LAB_CMD_PORT    = 5012            # CI_LAB UDP uplink port (CI_LAB_BASE_UDP_PORT)
LISTEN_HOST        = "0.0.0.0"      # Listen on all interfaces
LISTEN_PORT        = 5013            # TO_LAB downlink port (cfgTLM_PORT in to_lab_app.h)
ENABLE_INTERVAL_WARM_S = 30          # Re-send enable every N sec until first packet received
ENABLE_INTERVAL_IDLE_S = 300         # Steady-state interval once TO_LAB is known to be forwarding
LOCKFILE           = "/tmp/nos3_god_view.lock"

# god_view stays the sole TO_LAB downlink destination (no contention with
# cosmos for the TO_LAB ENABLE_OUTPUT slot). cosmos still needs SAT_HELLO
# samples for the GNSS GS Responder background task, so we mirror each
# packet to a side channel. ci_launch.sh maps cosmos UDP 5013 -> host UDP
# 5113, so sending here lands in cosmos's DEBUG interface read socket.
# Override via NOS3_TLM_MIRROR_DEST="host:port" or "off" to disable.
def _resolve_mirror_dest() -> tuple[str, int] | None:
    raw = os.environ.get("NOS3_TLM_MIRROR_DEST", "127.0.0.1:5113").strip()
    if not raw or raw.lower() == "off":
        return None
    host, _, port_s = raw.partition(":")
    try:
        return host or "127.0.0.1", int(port_s) if port_s else 5113
    except ValueError:
        return None
MIRROR_DEST = _resolve_mirror_dest()

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE   = os.path.join(SCRIPT_DIR, "..", "attack_logs", "cfs_god_view.json")
DECODED_FILE  = os.path.join(SCRIPT_DIR, "..", "omni_logs",   "tlm_hk_decoded.log")
MID_REGISTRY  = os.path.join(SCRIPT_DIR, "..", "cfg", "build", "mid_registry.json")

# ---------------------------------------------------------------------------
# HK payload decode table
#
# Keyed by the symbolic MID name (e.g. "GENERIC_EPS_HK_TLM_MID"). The actual
# integer MID and subsystem label are resolved at startup by looking the name
# up in cfg/build/mid_registry.json, which is regenerated by `make config`
# (see scripts/mid/gen_mid_registry.py). If a topic ID changes in an
# FSW header, re-running `make config` is all that is needed here.
#
# Value: (app_name, [(field, byte_offset, struct_fmt), ...])
# Offsets are from the start of the CCSDS packet (primary header at 0).
# CFE_MSG_TelemetryHeader_t is 16 bytes in this Draco build:
# CCSDS Primary (6) + TelemetrySecondaryHeader (6 bytes Time) + Spare[4].
# Verified empirically by hex-dumping a live MGR HK packet (byte 18 == 0x03
# after MGR set SpacecraftMode = 3) and an EPS HK packet (uint16 LE at
# byte 20 == 25199 mV, matching the sim's Battery Voltage debug print).
# ---------------------------------------------------------------------------
_DECODE_BY_NAME: dict = {
    "HS_HK_TLM_MID": ("HS", [
        ("cmd_count",         16, "B"),
        ("cmd_err_count",     17, "B"),
        ("resets_performed",  24, "<H"),  # ResetsPerformed (uint16 LE). Payload
                                          # has 8 bytes of u8 state before this
                                          # (cmd ctrs + 6 mon-state bytes + Spare).
        ("cpu_avg_pct",       44, "<I"),  # UtilCpuAvg stored as pct*100 uint32
        ("cpu_peak_pct",      48, "<I"),  # UtilCpuPeak stored as pct*100 uint32
    ]),
    "LC_HK_TLM_MID": ("LC", [
        ("cmd_count",      16, "B"),
        ("cmd_err_count",  17, "B"),
        ("lc_state",       18, "B"),
    ]),
    "SC_HK_TLM_MID": ("SC", [
        ("curr_ats_id",    16, "B"),
        ("num_rts_active", 24, "<H"),
        ("rts_active_ctr", 28, "<H"),
    ]),
    "HK_HK_TLM_MID": ("HK", [
        ("cmd_count",      16, "B"),
        ("cmd_err_count",  17, "B"),
    ]),
    "TO_LAB_HK_TLM_MID": ("TO_LAB", [
        ("cmd_count",      16, "B"),   # CommandCounter
        ("cmd_err_count",  17, "B"),   # CommandErrorCounter
    ]),
    "GENERIC_EPS_HK_TLM_MID": ("EPS", [
        ("battery_mv",     20, "<H"),   # BatteryVoltage in DeviceHK payload
        ("solar_array_mv", 32, "<H"),   # SolarArrayVoltage in DeviceHK payload
    ]),
    "MGR_HK_TLM_MID": ("MGR", [
        ("spacecraft_mode", 18, "B"),   # SpacecraftMode (uint8)
        ("sci_pass_count",  32, "<H"),  # SciPassCount (uint16 LE)
    ]),
    # GENERIC_GNSS_HK_TLM_MID payload layout (after the 16-byte
    # CFE_MSG_TelemetryHeader_t):
    #   16: CommandErrorCount (B)
    #   17: CommandCount (B)
    #   18: DeviceErrorCount (B)
    #   19: DeviceCount (B)
    #   20: DeviceEnabled (B)
    #   21: SolutionType (B)        ──  start of DeviceHK
    #   22: NumSatsTotal (B)
    #   23: NumSatsGps (B)
    #   24: NumSatsGlonass (B)
    #   25: NumSatsGalileo (B)
    #   26: NumSatsBeidou (B)
    #   27: Pdop (<f)
    #   31: Hdop (<f)
    #   35: Vdop (<f)
    #   39: GnssLat (<d)            ──  appended for GNSS-to-GS validation
    #   47: GnssLon (<d)
    #   55: InDenmarkBox (B)
    #   56: InScienceMode (B)
    #   57: LastPingSeq (<I)
    #   61: LastPingTime (<Q)
    #   69: PingCount (<I)
    "GENERIC_GNSS_HK_TLM_MID": ("GENERIC_GNSS", [
        ("cmd_count",        17, "B"),
        ("gnss_lat",         39, "<d"),
        ("gnss_lon",         47, "<d"),
        ("in_denmark_box",   55, "B"),
        ("in_science_mode",  56, "B"),
        ("last_ping_seq",    57, "<I"),
        ("last_ping_time",   61, "<Q"),
        ("ping_count",       69, "<I"),
    ]),
    "CFE_ES_HK_TLM_MID":    ("CFE_ES",   [("cmd_count", 16, "B")]),
    "CFE_SB_HK_TLM_MID":    ("CFE_SB",   [("cmd_count", 16, "B")]),
    "CFE_TIME_HK_TLM_MID":  ("CFE_TIME", [("cmd_count", 16, "B")]),
    "NOVATEL_OEM615_HK_TLM_MID": ("GPS", [("cmd_count", 16, "B")]),
    "SCH_HK_TLM_MID":       ("SCH",      [("cmd_count", 16, "B")]),

    # Sensor DEVICE_TLM payloads. Each payload starts at offset 16 (after the
    # 16-byte CFE_MSG_TelemetryHeader_t). Field offsets verified against the
    # packed Device_Data_tlm_t structs in components/<sensor>/fsw/shared/*_device.h
    # at this Draco snapshot. Names match the existing TSVB visualisations
    # (mag_x..., imu_acc_x..., fss_alpha, st_q0..., rw_momentum_*, ...).
    "GENERIC_MAG_DEVICE_TLM_MID": ("MAG", [
        ("mag_x",          16, "<i"),   # int32 MagneticIntensityX
        ("mag_y",          20, "<i"),
        ("mag_z",          24, "<i"),
    ]),
    "GENERIC_IMU_DEVICE_TLM_MID": ("IMU", [
        ("imu_acc_x",      16, "<f"),   # X.LinearAcc
        ("imu_gyro_x",     20, "<f"),   # X.AngularAcc
        ("imu_acc_y",      24, "<f"),
        ("imu_gyro_y",     28, "<f"),
        ("imu_acc_z",      32, "<f"),
        ("imu_gyro_z",     36, "<f"),
    ]),
    "GENERIC_FSS_DEVICE_TLM_MID": ("FSS", [
        ("fss_alpha",      16, "<f"),
        ("fss_beta",       20, "<f"),
        ("fss_error_code", 24, "B"),
    ]),
    "GENERIC_CSS_DEVICE_TLM_MID": ("CSS", [
        ("css_voltage_0",  16, "<H"),
        ("css_voltage_1",  18, "<H"),
        ("css_voltage_2",  20, "<H"),
        ("css_voltage_3",  22, "<H"),
        ("css_voltage_4",  24, "<H"),
        ("css_voltage_5",  26, "<H"),
    ]),
    "SAMPLE_DEVICE_TLM_MID": ("SAMPLE", [
        ("sample_counter",   16, "<I"),
        ("sample_x",         20, "<H"),
        ("sample_y",         22, "<H"),
        ("sample_z",         24, "<H"),
        ("sample_pass_num",  26, "<H"),
        ("sample_region",    28, "B"),
    ]),
    "GENERIC_STAR_TRACKER_DEVICE_TLM_MID": ("STAR_TRACKER", [
        ("st_q0",          16, "<d"),
        ("st_q1",          24, "<d"),
        ("st_q2",          32, "<d"),
        ("st_q3",          40, "<d"),
        ("st_valid",       48, "B"),
    ]),
    # RW HK payload (no separate DEVICE TLM): 11 uint8 counters + double[3] momenta.
    # Fields at fixed offsets after the 16-byte TLM header. The packed outer
    # struct does not realign the inner GENERIC_RW_Data, so the doubles start
    # right after the 11 counter bytes (offset 27).
    "GENERIC_RW_APP_HK_TLM_MID": ("RW", [
        ("rw_cmd_err_count",   16, "B"),
        ("rw_cmd_count",       17, "B"),
        ("rw0_dev_err_count",  18, "B"),
        ("rw1_dev_err_count",  19, "B"),
        ("rw2_dev_err_count",  20, "B"),
        ("rw0_dev_count",      21, "B"),
        ("rw1_dev_count",      22, "B"),
        ("rw2_dev_count",      23, "B"),
        ("rw0_enabled",        24, "B"),
        ("rw1_enabled",        25, "B"),
        ("rw2_enabled",        26, "B"),
        ("rw0_momentum",       27, "<d"),
        ("rw1_momentum",       35, "<d"),
        ("rw2_momentum",       43, "<d"),
    ]),
}


def _load_decode_table() -> dict:
    """Resolve symbolic MID names -> integer MIDs via mid_registry.json."""
    try:
        with open(MID_REGISTRY) as fh:
            registry = json.load(fh)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"[god_view] WARN: cannot read {MID_REGISTRY}: {exc}",
              file=sys.stderr)
        return {}
    name_to_mid = {entry["name"]: (int(hex_key, 16), entry["subsystem"])
                   for hex_key, entry in registry.items()}
    out: dict = {}
    for name, (app, fields) in _DECODE_BY_NAME.items():
        resolved = name_to_mid.get(name)
        if resolved is None:
            print(f"[god_view] WARN: {name} not in MID registry; "
                  f"decode skipped", file=sys.stderr)
            continue
        mid_int, subsystem = resolved
        out[mid_int] = (app, subsystem, fields)
    return out


DECODE_TABLE: dict = _load_decode_table()

_CPU_PCT_FIELDS = {"cpu_avg_pct", "cpu_peak_pct"}


def _scrub_nan(value):
    # NaN / +-Inf float fields appear when FSW publishes HK before the bus
    # mirror has cached a real sample (GnssLat/GnssLon default to NaN until the
    # GNSS sim's first UART line is parsed). Python's json.dumps emits these as
    # the literal token "NaN" which is rejected by Logstash's json codec, so
    # the entire HK record is dropped with _jsonparsefailure. Replace with
    # None so the line stays valid JSON and downstream still reflects "no
    # value yet" via a null field. Walk dicts and lists recursively so a future
    # nested HK shape (or a list of payload samples) cannot reintroduce the
    # regression.
    if isinstance(value, float):
        return None if not math.isfinite(value) else value
    if isinstance(value, dict):
        return {k: _scrub_nan(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_scrub_nan(v) for v in value]
    return value


def decode_payload(data: bytes, header: dict) -> dict | None:
    """Decode payload fields from a CCSDS packet using DECODE_TABLE.

    Returns a record dict ready for JSON serialisation, or None if the MID
    has no decode entry or the packet is too short.
    """
    mid_int = int(header["msg_id"], 16)
    entry = DECODE_TABLE.get(mid_int)
    if entry is None or len(data) < 14:
        return None
    app_name, subsystem, fields = entry
    record: dict = {
        "type":      "hk_decoded",
        "app":       app_name,
        "subsystem": subsystem,
        "msg_id":    header["msg_id"],
        "timestamp": header["timestamp"],
        "sequence":  header["sequence"],
    }
    for field_name, offset, fmt in fields:
        size = struct.calcsize(fmt)
        if len(data) >= offset + size:
            (val,) = struct.unpack_from(fmt, data, offset)
            if field_name in _CPU_PCT_FIELDS:
                if val == 0xFFFFFFFF:
                    continue
                val = round(val / 100.0, 2)
            record[field_name] = val
    return record

# ---------------------------------------------------------------------------
# TO_LAB_OUTPUT_ENABLE_CC (CC=2) command packet.
# CI_LAB is a UDP-to-SB bridge: it reads any CCSDS packet from UDP and
# publishes it onto the Software Bus unchanged.  The SB routes by the CCSDS
# stream_id (APID), so we must use TO_LAB_CMD_MID (0x18E8) - not CI_LAB's
# own MID - so the SB delivers the enable command to TO_LAB, not back to CI_LAB.
# ---------------------------------------------------------------------------
TO_LAB_CMD_MID = 0x18E8             # TO_LAB_CMD_MID from to_lab_msgids.h


def build_enable_cmd(dest_ip: str) -> bytes:
    """
    Build a TO_LAB_OUTPUT_ENABLE_CC command.
    CI_LAB bridges UDP→SB unchanged, so the stream_id must be TO_LAB_CMD_MID
    so the SB routes it to TO_LAB, not back to CI_LAB.
    Payload is a 20-byte destination IP string (null-padded).
    CCSDS primary header data_length = secondary_hdr(2) + payload(20) - 1 = 21 (0x0015).
    """
    ip_bytes = dest_ip.encode("ascii")[:20].ljust(20, b"\x00")
    hdr = struct.pack(
        ">HHHBB",
        TO_LAB_CMD_MID,  # 0x18E8 - routes to TO_LAB on the SB
        0xC000,          # sequence counter + command type flag
        0x0015,          # data_length = 2 (sec hdr) + 20 (IP) - 1 = 21
        0x02,            # TO_LAB_OUTPUT_ENABLE_CC
        0x00,            # checksum (not validated in simulation)
    )
    return hdr + ip_bytes


def send_enable(listen_ip: str) -> None:
    """Send TO_LAB_OUTPUT_ENABLE_CC to CI_LAB."""
    cmd = build_enable_cmd(listen_ip)
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
        s.sendto(cmd, (CI_LAB_HOST, CI_LAB_CMD_PORT))


def enable_loop(listen_ip: str, stop_event: threading.Event,
                telemetry_seen: threading.Event) -> None:
    """Periodically re-send the enable command until stop_event is set.

    Uses a short warm-up interval until the first telemetry packet is seen, then
    switches to a long idle interval to avoid flooding TO_LAB_CMD_PIPE with
    repeated ENABLE commands (which produce CFE_SB Msg Limit Err events).
    """
    while not stop_event.is_set():
        try:
            send_enable(listen_ip)
        except OSError as exc:
            print(f"[god_view] enable send error: {exc}", file=sys.stderr)
        interval = ENABLE_INTERVAL_IDLE_S if telemetry_seen.is_set() else ENABLE_INTERVAL_WARM_S
        stop_event.wait(interval)


# ---------------------------------------------------------------------------
# Sensor activation + DEVICE_TLM polling
#
# The mission RTSes only enable a subset of sensors (TORQUER, ST, SAMPLE, RW),
# and the SCH table only sends GENERIC_*_REQ_HK_TLM (FC=0) to MAG/IMU/FSS/CSS,
# which makes those apps publish HK counters but NEVER their DEVICE_TLM payload
# (the one with the actual sensor values). Without DEVICE_TLM packets the
# Sensor Ground Truth dashboard cannot populate mag_x, imu_acc_x, fss_alpha,
# st_q*, etc.
#
# This loop pokes the FSW once at startup with GENERIC_*_ENABLE_CC and then
# periodically issues GENERIC_*_REQ_HK_MID with FC=GENERIC_*_REQ_DATA_TLM
# (FC=1) so each app publishes its DEVICE_TLM_MID. CI_LAB bridges UDP -> SB
# unchanged, so the stream_id we send must be the app's *_REQ_HK_MID (the
# pipe each app subscribes to) and FC=1 selects the device-data branch.
# ---------------------------------------------------------------------------
SENSOR_ENABLES = [
    # (cmd_mid,  enable_cc, name)
    (0x192A, 2, "GENERIC_MAG"),
    (0x1925, 2, "GENERIC_IMU"),
    (0x1920, 2, "GENERIC_FSS"),
    (0x1910, 2, "GENERIC_CSS"),
    (0x18FA, 2, "SAMPLE"),
    (0x18EA, 2, "GENERIC_THRUSTER"),
    (0x1935, 2, "GENERIC_STAR_TRACKER"),
]

# (req_hk_mid, name) -- FC=1 = REQ_DATA_TLM for these generic-pattern apps.
SENSOR_DATA_POLLS = [
    (0x192B, "GENERIC_MAG"),       # GENERIC_MAG_REQ_HK_MID
    (0x1926, "GENERIC_IMU"),       # GENERIC_IMU_REQ_HK_MID
    (0x1921, "GENERIC_FSS"),       # GENERIC_FSS_REQ_HK_MID
    (0x1911, "GENERIC_CSS"),       # GENERIC_CSS_REQ_HK_MID
    (0x18FB, "SAMPLE"),            # SAMPLE_REQ_HK_MID
]
SENSOR_POLL_INTERVAL_S = 2.0


def _build_no_payload_cmd(mid: int, cc: int) -> bytes:
    """Pack a CCSDS command packet with no payload (header + cc + checksum)."""
    return struct.pack(
        ">HHHBB",
        mid,
        0xC000,   # seq counter + cmd type flag
        0x0001,   # data_length = sec_hdr(2) + payload(0) - 1 = 1
        cc,
        0x00,
    )


def sensor_loop(stop_event: threading.Event) -> None:
    """Activate non-default sensors once, then drive DEVICE_TLM publication.

    Sends ENABLE commands at startup so MAG/IMU/FSS/CSS/SAMPLE start polling
    their simulated devices. Then every SENSOR_POLL_INTERVAL_S sends FC=1
    (REQ_DATA_TLM) commands so each app publishes a DEVICE_TLM_MID packet
    that TO_LAB forwards back to god_view for decoding.
    """
    # Brief warm-up so cFS finishes app init before the first commands arrive.
    if stop_event.wait(8):
        return

    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            for mid, cc, name in SENSOR_ENABLES:
                s.sendto(_build_no_payload_cmd(mid, cc),
                         (CI_LAB_HOST, CI_LAB_CMD_PORT))
            print(f"[god_view] Sent ENABLE_CC to {len(SENSOR_ENABLES)} sensors",
                  flush=True)
    except OSError as exc:
        print(f"[god_view] sensor enable error: {exc}", file=sys.stderr)

    while not stop_event.is_set():
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
                for mid, _name in SENSOR_DATA_POLLS:
                    s.sendto(_build_no_payload_cmd(mid, 1),
                             (CI_LAB_HOST, CI_LAB_CMD_PORT))
        except OSError as exc:
            print(f"[god_view] sensor poll error: {exc}", file=sys.stderr)
        stop_event.wait(SENSOR_POLL_INTERVAL_S)


def parse_primary_header(data: bytes) -> dict | None:
    """
    Parse a CCSDS primary header (6 bytes).
    Returns a dict with msg_id, sequence, length, and timestamp fields,
    or None if the packet is too short.
    """
    if len(data) < 6:
        return None
    stream_id, seq_ctrl, data_len = struct.unpack_from(">HHH", data, 0)
    apid      = stream_id & 0x07FF
    pkt_type  = (stream_id >> 12) & 0x01   # 1=command, 0=telemetry
    seq_count = seq_ctrl & 0x3FFF
    total_len = data_len + 7               # CCSDS: data_length = total - 7

    mid = stream_id
    record = {
        "msg_id":        f"0x{mid:04X}",
        "apid":          apid,
        "pkt_type":      "CMD" if pkt_type else "TLM",
        "sequence":      seq_count,
        "length":        total_len,
        "timestamp":     time.time(),
    }
    # cFS commands carry the function code at byte offset 6 (just after the
    # 6-byte CCSDS primary header). Capture it on CMD packets so logstash can
    # tag specific function codes (e.g. GENERIC_GNSS_GS_PING_CC = fc=4) and
    # not just by MID. TLM packets have a time-stamp here, so skip on TLM.
    if pkt_type and len(data) >= 7:
        record["function_code"] = data[6]
    return record


def _acquire_singleton_lock():
    """Acquire an exclusive advisory lock so only one capture runs at a time.

    Returns the open file object (must be kept alive for the lifetime of the
    process to hold the lock). If another instance is already running, prints a
    clear message and exits 0 so the Makefile background spawn stays quiet.
    """
    lock_fh = open(LOCKFILE, "w")
    try:
        fcntl.flock(lock_fh.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        print(f"[god_view] Another instance already holds {LOCKFILE}; exiting.",
              file=sys.stderr)
        lock_fh.close()
        sys.exit(0)
    lock_fh.write(f"{os.getpid()}\n")
    lock_fh.flush()
    return lock_fh


def main() -> None:
    lock_fh = _acquire_singleton_lock()

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    os.makedirs(os.path.dirname(DECODED_FILE), exist_ok=True)

    # Determine the host IP on the nos3-core network so TO_LAB knows where
    # to send packets.  Fall back to a loopback address if unavailable.
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as _s:
            _s.connect((CI_LAB_HOST, CI_LAB_CMD_PORT))
            listen_ip = _s.getsockname()[0]
    except OSError:
        listen_ip = "127.0.0.1"

    print(f"[god_view] Listening on {listen_ip}:{LISTEN_PORT}", flush=True)
    print(f"[god_view] Sending TO_LAB enable to {CI_LAB_HOST}:{CI_LAB_CMD_PORT}", flush=True)
    print(f"[god_view] Output: {OUTPUT_FILE}", flush=True)
    out_sz = os.path.getsize(OUTPUT_FILE) if os.path.exists(OUTPUT_FILE) else 0
    dec_sz = os.path.getsize(DECODED_FILE) if os.path.exists(DECODED_FILE) else 0
    print(f"[god_view] OUTPUT_FILE size at start  = {out_sz} bytes", flush=True)
    print(f"[god_view] DECODED_FILE size at start = {dec_sz} bytes", flush=True)
    if MIRROR_DEST is not None:
        print(f"[god_view] Mirroring downlink to {MIRROR_DEST[0]}:{MIRROR_DEST[1]}", flush=True)

    stop_event = threading.Event()
    telemetry_seen = threading.Event()

    def _sighandler(sig, frame):   # noqa: ANN001
        print("[god_view] Shutting down.", file=sys.stderr)
        stop_event.set()

    signal.signal(signal.SIGTERM, _sighandler)
    signal.signal(signal.SIGINT,  _sighandler)

    enable_thread = threading.Thread(
        target=enable_loop, args=(listen_ip, stop_event, telemetry_seen),
        daemon=True,
    )
    enable_thread.start()

    sensor_thread = threading.Thread(
        target=sensor_loop, args=(stop_event,), daemon=True,
    )
    sensor_thread.start()

    mirror_sock = None
    mirror_warned = False
    if MIRROR_DEST is not None:
        mirror_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    # Open output files in append mode so previous runs are not erased.
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock, \
         open(OUTPUT_FILE,  "a", buffering=1) as out_fh, \
         open(DECODED_FILE, "a", buffering=1) as decoded_fh:

        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((LISTEN_HOST, LISTEN_PORT))
        sock.settimeout(1.0)

        while not stop_event.is_set():
            try:
                data, _addr = sock.recvfrom(65535)
            except socket.timeout:
                continue
            except OSError as exc:
                print(f"[god_view] recv error: {exc}", file=sys.stderr)
                break

            if mirror_sock is not None:
                try:
                    mirror_sock.sendto(data, MIRROR_DEST)
                except OSError as exc:
                    if not mirror_warned:
                        print(f"[god_view] mirror send error to {MIRROR_DEST}: {exc}",
                              file=sys.stderr)
                        mirror_warned = True

            record = parse_primary_header(data)
            if record is None:
                continue

            telemetry_seen.set()
            out_fh.write(json.dumps(_scrub_nan(record)) + "\n")

            decoded = decode_payload(data, record)
            if decoded is not None:
                decoded_fh.write(json.dumps(_scrub_nan(decoded)) + "\n")

    if mirror_sock is not None:
        mirror_sock.close()

    stop_event.set()
    enable_thread.join(timeout=2)
    sensor_thread.join(timeout=2)
    try:
        fcntl.flock(lock_fh.fileno(), fcntl.LOCK_UN)
        lock_fh.close()
        os.unlink(LOCKFILE)
    except OSError:
        pass
    print("[god_view] Done.")


if __name__ == "__main__":
    main()
